services:
  db:
    image: postgres:16-alpine
    container_name: digital_minimalist_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_minimalist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  stripe-cli:
    build:
      context: .
      dockerfile: Dockerfile.stripe
    container_name: digital_minimalist_stripe_cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name docker-stripe-cli --forward-to web:8000/payments/webhook/"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - web

  qcluster:
    build: .
    container_name: digital_minimalist_qcluster
    command: python manage.py qcluster
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/digital_minimalist_db


  web:
    build: .
    container_name: digital_minimalist_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/digital_minimalist_db

volumes:
  postgres_data:
